spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: HJH19991228
    driver-class-name: com.mysql.cj.jdbc.Driver

  #关闭缓存
  thymeleaf:
    cache: false


  mvc:
    static-path-pattern=/static/: